/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoreBeliefsRouteImport } from './routes/core-beliefs'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WatchAndLearnRouteImport } from './routes/watch-and-learn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreBeliefsRoute = CoreBeliefsRouteImport.update({
  id: '/core-beliefs',
  path: '/core-beliefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchAndLearnRoute = WatchAndLearnRouteImport.update({
  id: '/watch-and-learn',
  path: '/watch-and-learn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/core-beliefs': typeof CoreBeliefsRoute
  '/services': typeof ServicesRoute
  '/watch-and-learn': typeof WatchAndLearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/core-beliefs': typeof CoreBeliefsRoute
  '/services': typeof ServicesRoute
  '/watch-and-learn': typeof WatchAndLearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/core-beliefs': typeof CoreBeliefsRoute
  '/services': typeof ServicesRoute
  '/watch-and-learn': typeof WatchAndLearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators'
    | '/career'
    | '/contact'
    | '/core-beliefs'
    | '/services'
    | '/watch-and-learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/career'
    | '/contact'
    | '/core-beliefs'
    | '/services'
    | '/watch-and-learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators'
    | '/career'
    | '/contact'
    | '/core-beliefs'
    | '/services'
    | '/watch-and-learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CoreBeliefsRoute: typeof CoreBeliefsRoute
  ServicesRoute: typeof ServicesRoute
  WatchAndLearnRoute: typeof WatchAndLearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-beliefs': {
      id: '/core-beliefs'
      path: '/core-beliefs'
      fullPath: '/core-beliefs'
      preLoaderRoute: typeof CoreBeliefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-and-learn': {
      id: '/watch-and-learn'
      path: '/watch-and-learn'
      fullPath: '/watch-and-learn'
      preLoaderRoute: typeof WatchAndLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsRoute: CalculatorsRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CoreBeliefsRoute: CoreBeliefsRoute,
  ServicesRoute: ServicesRoute,
  WatchAndLearnRoute: WatchAndLearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
